# LEGACY PROBLEM: Multiple deployment models / Global Multi-Cloud.
# Profile "postgres" — production-like PostgreSQL region (EU / APAC pods).
spring.datasource.url=jdbc:postgresql://localhost:5432/erm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=erm
spring.datasource.password=erm
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL10Dialect
spring.h2.console.enabled=false
